-- Temporary fix for development: Disable RLS on admin tables
-- Run this in Supabase SQL Editor for development

ALTER TABLE articles DISABLE ROW LEVEL SECURITY;
ALTER TABLE insights DISABLE ROW LEVEL SECURITY;
ALTER TABLE podcasts DISABLE ROW LEVEL SECURITY;
ALTER TABLE events DISABLE ROW LEVEL SECURITY;
ALTER TABLE training DISABLE ROW LEVEL SECURITY;
ALTER TABLE newsletters DISABLE ROW LEVEL SECURITY;
ALTER TABLE newsletter_subscribers DISABLE ROW LEVEL SECURITY;

-- Note: Re-enable RLS before production deployment!
-- ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE insights ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE podcasts ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE events ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE training ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE newsletters ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;
